import gateway.link


udp_upload_ais = gateway.link.SqlFileModbusData(
    channels = {155}, #,152},
    start_delay = 0,
    transmit_rate = 0.5,
    max_age = 20,
    target_channels = {'SLAVE-001':{0:'txt', 156:'json'}},
    message_formats = [ {"message": {"type":"FC03", "start_pos":0},
                     "VL1N": { "bits":[  0,  1], "type":"f", "round":2 },
                     "VL2N": { "bits":[  2,  3], "type":"f", "round":2 },
                     "VL3N": { "bits":[  4,  5], "type":"f", "round":2 },
                     "VL12": { "bits":[  6,  7], "type":"f", "round":2 },
                     "VL23": { "bits":[  8,  9], "type":"f", "round":2 },
                     "VL31": { "bits":[ 10, 11], "type":"f", "round":2 },
                     "IL1":  { "bits":[ 12, 13], "type":"f", "round":2 },
                     "IL2":  { "bits":[ 14, 15], "type":"f", "round":2 },
                     "IL3":  { "bits":[ 16, 17], "type":"f", "round":2 },
                     "IN":   { "bits":[ 18, 19], "type":"f", "round":2 },
                     "P1":   { "bits":[ 20, 21], "type":"f", "round":2, "div": -1000 },
                     "P2":   { "bits":[ 22, 23], "type":"f", "round":2, "div": -1000 },
                     "P3":   { "bits":[ 24, 25], "type":"f", "round":2, "div": -1000 },
                     "S1":   { "bits":[ 26, 27], "type":"f", "round":2, "div": 1000 },
                     "S2":   { "bits":[ 28, 29], "type":"f", "round":2, "div": 1000 },
                     "S3":   { "bits":[ 30, 31], "type":"f", "round":2, "div": 1000 },
                     "Q1":   { "bits":[ 32, 33], "type":"f", "round":2, "div": -1000 },
                     "Q2":   { "bits":[ 34, 35], "type":"f", "round":2, "div": -1000 },
                     "Q3":   { "bits":[ 36, 37], "type":"f", "round":2, "div": -1000 },
                     "PH":   { "bits":[ 38, 39], "type":"f", "round":0 },
                     "PF1":  { "bits":[ 40, 41], "type":"f", "round":3 },
                     "PF2":  { "bits":[ 42, 43], "type":"f", "round":3 },
                     "PF3":  { "bits":[ 44, 45], "type":"f", "round":3 },
                     "VLN":  { "bits":[ 46, 47], "type":"f", "round":3 },
                     "VLL":  { "bits":[ 48, 49], "type":"f", "round":3 },
                     "P":    { "bits":[ 50, 51], "type":"f", "round":2, "div": -1000 },
                     "S":    { "bits":[ 52, 53], "type":"f", "round":2, "div": 1000  },
                     "Q":    { "bits":[ 54, 55], "type":"f", "round":2, "div": -1000 },
                     "PF":   { "bits":[ 56, 57], "type":"f", "round":3 },
                     "F":    { "bits":[ 58, 59], "type":"f", "round":3 },
                     "SS":   { "function":{"name":"apparent_power_sign_from_active_power", "args":{"S", "P"}} },
                     "IL":   { "function":{"name":"average_line_current", "args":{"IL1", "IL2", "IL3"}} },
                     "ILS":  { "function":{"name":"line_current_sign_from_active_power", "args":{"IL", "P"}} }  } ],
    config_filename = 'conf_cloud_db.ini')

udp_upload_ais.run()
