import gateway.link


udp_upload_ais = gateway.link.SqlHttpUpdateStatic(
    channels = {172},
    start_delay = 0,
    transmit_rate = 0.2,
    max_age = 10,
    max_connect_attempts = 50,
    message_formats = [ {"message": {"type":5},
                     "imo":          { "type":"int", "novalue":0 },
                     "callsign":     { "type":"str" },
                     "shipname":     { "type":"str" },
                     "shiptype":     { "type":"int", "novalue":0 },
                     "to_bow":       { "type":"int", "novalue":0, "overflow":511 },
                     "to_stern":     { "type":"int", "novalue":0, "overflow":511 },
                     "to_port":      { "type":"int", "novalue":0, "overflow":63 },
                     "to_starboard": { "type":"int", "novalue":0, "overflow":63 },
                     "month":        { "type":"int", "novalue":0 },
                     "day":          { "type":"int", "novalue":0 },
                     "hour":         { "type":"int", "novalue":24 },
                     "minute":       { "type":"int", "novalue":60 },
                     "draught":      { "type":"float", "round": 1, "novalue":0 },
                     "destination":  { "type":"str" },
                     "device_hardware_id": { "function":{"name":"create_key", "args":{"mmsi"}} },
                     "host_hardware_id": { "function":{"name":"get_host_hardware_id", "args":{"imo", "shipname", "callsign", "mmsi"}} },
                     "image_filename":{ "function":{"name":"get_png_name_by_key", "args":{"mmsi"}} } },
                     {"message": {"type":[1,2,3]},
                      "status":       { "type":"int", "novalue":15 },
                      "turn":         { "type":"float", "round":1, "novalue":-128, "underflow":-127, "overflow":127 },
                      "speed":        { "type":"float", "round":1, "novalue":1023, "overflow":1022 },
                      "accuracy":     { "type":"bool" },
                      "lon":          { "type":"float", "round":5, "novalue":181 },
                      "lat":          { "type":"float", "round":5, "novalue":91 },
                      "course":       { "type":"float", "round":1, "novalue":360 },
                      "heading":      { "type":"float", "round":1, "novalue":511 },
                      "second":       { "type":"int", "novalue":[61,62,63], "nosensor":60 },
                      "device_hardware_id": { "function":{"name":"create_key", "args":{"mmsi"}} },
                      "image_filename":{ "function":{"name":"get_png_name_by_key", "args":{"mmsi"}} } } ],
    config_filepath = '/srv/dogger/',
    config_filename = 'conf_cloud_db.ini')

udp_upload_ais.run()
